### ISSUE TITLE
Updating CTDcast kernel to maximum depth

### ISSUE THREAD

**Issue by erikvansebille** [OceanParcels/Virtual_ship_classroom#11]
There's still an old comment in `CTDcast` kernel that limits sampling to 200 m. Needs to be updated before VirtualShip works?

https://github.com/OceanParcels/Virtual_ship_classroom/blob/b9a1dbffb1e0389bf02e14babfb732d677efa157/virtualship.py#L190

**Comment by ammedd** [comment]
Added max depth to the JSON file and updated code
