### ISSUE TITLE
Specify ADCP to VM-ADCP?

### ISSUE THREAD

**Issue by erikvansebille** [OceanParcels/Virtual_ship_classroom#13]
Since there are many types of ADCP (lowered, bottom-lander, ...), it might be good to specify throughout that we mean VM-ADCP (Vessel-Mounted)

https://github.com/OceanParcels/Virtual_ship_classroom/blob/b9a1dbffb1e0389bf02e14babfb732d677efa157/virtualship.py#L214

**Comment by ammedd** [comment]
Definitely!
