### ISSUE TITLE
More leniency on max time for CTD cast

### ISSUE THREAD

**Issue by erikvansebille** [OceanParcels/Virtual_ship_classroom#15]
The maximum time-length of a CTD-cast is now set to 4 hours, which can be quite short for very deep casts. Make this a bit higher, so that they don't stop halfway?

https://github.com/OceanParcels/Virtual_ship_classroom/blob/b9a1dbffb1e0389bf02e14babfb732d677efa157/virtualship.py#L261

**Comment by ammedd** [comment]
Definitely!
