### ISSUE TITLE
Use fieldset.constants to set constant variables in Kernels

### ISSUE THREAD

**Issue by erikvansebille** [OceanParcels/Virtual_ship_classroom#16]
I'm surprised that this works, with `config.`:
https://github.com/OceanParcels/Virtual_ship_classroom/blob/b9a1dbffb1e0389bf02e14babfb732d677efa157/virtualship.py#L317-L321

Normally, I would use 
```python
driftdepth = fieldset.driftdepth  # maximum depth in m 
```
and then in the Fieldset creation
```python
fieldset.add_constant('driftdepth', config.driftdepth)
```

**Comment by ammedd** [comment]
It doesn't ;-) Argo was untested. I'll change according to your suggestions.
I still get an Error during compilation:
In function 'ArgoVerticalMovementAdvectionRK4KeepAtSurface':
 error: 'vertical_speed' redeclared as different kind of symbol
   87 |   type_coord vertical_speed = 0;
      |              ^~~~~~~~~~~~~~
 note: previous definition of 'vertical_speed' with type 'float'

**Comment by erikvansebille** [comment]
> `note: previous definition of 'vertical_speed' with type 'float'`

Apparently there is another definition of vertical_speed in this or one of the other kernels?

**Comment by erikvansebille** [comment]
Although it's strange that this would be the cause of the error because you never combine the CTDcast and ArgoVerticalMovement kernels...

**Comment by ammedd** [comment]
Changed the CTD to winch_speed, doesn't solve the error...

**Comment by ammedd** [comment]
Ha Emma, ik heb de bug zojuist gefixt, en een update naar GitHub gepusht. Het probleem was dat de naam van de variabele (`vertical_speed`) hetzelfde was als de naam van de fieldset-constant. Dat zorgde voor verwarring. Ik zal een Issue aanmaken dat de error duidelijker wordt weergegeven. De oplossing is om de naam van de variabelen te veranderen, of (zoals ik heb gedaan) direct de fieldset-constants te gebruiken in de kernel code
