### ISSUE TITLE
Remove old, unused code?

### ISSUE THREAD

**Issue by erikvansebille** [OceanParcels/Virtual_ship_classroom#17]
The lines below are commented out and perhaps not necessary? Can be removed?

https://github.com/OceanParcels/Virtual_ship_classroom/blob/b9a1dbffb1e0389bf02e14babfb732d677efa157/virtualship.py#L429-L431

**Comment by ammedd** [comment]
Well.. it would be good to reconsider the "noise" for the CTD and think about if and how to implement this for the Argo floats as well. I'll leave the code and this issue open for now as a reminder. Ideas are welcome
