### ISSUE TITLE
Directory/file selection may not work on Windows?

### ISSUE THREAD

**Issue by erikvansebille** [OceanParcels/Virtual_ship_classroom#19]
The virtualshiv now uses a `/` to combine directory and filename for the netcdf-files, but on windows this needs to be a `\`
https://github.com/OceanParcels/Virtual_ship_classroom/blob/bd1c30fd26b49bf3e173b1fd48c47f42184f366c/virtualship.py#L139-L142
And 
https://github.com/OceanParcels/Virtual_ship_classroom/blob/bd1c30fd26b49bf3e173b1fd48c47f42184f366c/virtualship.py#L155

Beter to use [`os.path.join()`](https://docs.python.org/3/library/os.path.html#os.path.join)?

**Comment by ammedd** [comment]
Definitely!
