### ISSUE TITLE
Missing check whether fieldset contains config.region_of_interest

### ISSUE THREAD

**Issue by erikvansebille** [OceanParcels/Virtual_ship_classroom#20]
While the `VirtualShipConfiguration()` class contains lots of checks whether the json file itself is consistent, there are no checks whether the fieldsets are also consistent with the json. That could of course be expected if the whole run is done in one go; but if the data downloading is separated from the virtual ship running (and the json file is changed between these operations), then users could get a `FieldOutOfBoundError` error.

Would it be useful to add an explicit check that region spanned by the `fieldset.U.lon` and `fieldset.U.lat` is equal to or larger than the config.region_of_interest?

For example by adding the code below?
```python
    if fieldset.U.lon.min() > config.region_of_interest["West"]:
        raise ValueError("FieldSet western boundary is within region of interest. Please run download_data.py again.")
    if fieldset.U.lon.max() < config.region_of_interest["East"]:
        raise ValueError("FieldSet eastern boundary is within region of interest. Please run download_data.py again.")
    if fieldset.U.lat.min() > config.region_of_interest["South"]:
        raise ValueError("FieldSet southern boundary is within region of interest. Please run download_data.py again.")
    if fieldset.U.lat.max() < config.region_of_interest["North"]:
        raise ValueError("FieldSet northern boundary is within region of interest. Please run download_data.py again.")
```

**Comment by ammedd** [comment]
Definitely useful. Added, but replaced within with outside ;-)
