### ISSUE TITLE
Ship and measurements on land

### ISSUE THREAD

**Issue by ammedd** [OceanParcels/Virtual_ship_classroom#25]
Currently the virtual ship and can "sail" on land and do CTD measurements/deployments...

A possible way to fix this is using status codes in the kernel loops
https://github.com/OceanParcels/parcels/blob/daf05b71174ba2c687bfe0468ed27e1e64f17d06/docs/examples/tutorial_kernelloop.ipynb#L300
Or check using the CMEMS input data? Or...

**Comment by erikvansebille** [comment]
For now, let's at least test if the WayPoints are not on land. Can be done by checking if FieldSet.U and FieldSet.V are not both zero (in which case it would be a land point)
