### ISSUE TITLE
Also support longitudes in [0, 360] degree range in json file?

### ISSUE THREAD

**Issue by erikvansebille** [OceanParcels/Virtual_ship_classroom#4]
The json file now expects longitude between -180 and 180. 
https://github.com/OceanParcels/Virtual_ship_classroom/blob/b9a1dbffb1e0389bf02e14babfb732d677efa157/virtualship.py#L27

However, it is (also) quite common to refer to longitudes between 0 and 360. Perhaps support that option too?

**Comment by ammedd** [comment]
Sure. Would you then have users specify that they give input between 0 and 360 with a true/false statement? Otherwise how would you know? For sure if one of the values is above 180, but that doesn't catch all cases.  
Solve with if... and ((lon - 180) % 360) - 180

**Comment by erikvansebille** [comment]
Well, any value above 180 can also be interpreted as between -180 and 0; so I would indeed simply use `lon = ((lon - 180) % 360) - 180`. Or would that give other problems?

Note that parcels deals with this under-the-hood, so you could also choose to accept _all_ longitudes, even ones higher than 360 (I think)
