### ISSUE TITLE
Support for Deep Argo too?

### ISSUE THREAD

**Issue by erikvansebille** [OceanParcels/Virtual_ship_classroom#5]
The Virtual Ship now expects Argo maximum depths to be > -2000m:

https://github.com/OceanParcels/Virtual_ship_classroom/blob/b9a1dbffb1e0389bf02e14babfb732d677efa157/virtualship.py#L70

However, the [Deep Argo](https://argo.ucsd.edu/expansion/deep-argo-mission/) project develops drifters that can go much deeper. Also support them here?

**Comment by ammedd** [comment]
Done. Thanks, hadn't seen that yet.
