### ISSUE TITLE
interactive loop

### ISSUE THREAD

**Issue by surgura** [OceanParcels/Virtual_ship_classroom#53]
Create an interactive loop that asks users to make decisions each time something unexpected happens. The remainder of the schedule including the first waypoint that fails is provided. The user has to input a new schedule to continue. At each decision point the software creates a checkpoint so the user can continue even when quitting the software.

**Comment by VeckoTheGecko** [comment]
@surgura do you think this is closed now that #60 is merged? Is there anything pending?

**Comment by surgura** [comment]
yeah I think we are good here
