### ISSUE TITLE
Support for positive Argo vertical speed

### ISSUE THREAD

**Issue by erikvansebille** [OceanParcels/Virtual_ship_classroom#6]
Since rising and sinking speed are the same in the Virtual Ship, why not also support a positive vertical speed here, but make sure it's converted to negative then?

https://github.com/OceanParcels/Virtual_ship_classroom/blob/b9a1dbffb1e0389bf02e14babfb732d677efa157/virtualship.py#L72-L73

**Comment by ammedd** [comment]
Sure. Done. And added some extra checks for reality, e.g. speed between 0.06 and 0.12 as in https://www.researchgate.net/figure/Histogram-of-the-average-float-ascent-speed-for-27000-BGC-Argo-radiometry-profiles_fig2_354631834
