### ISSUE TITLE
Explain ADCP distance criteria better

### ISSUE THREAD

**Issue by erikvansebille** [OceanParcels/Virtual_ship_classroom#7]
I'm not sure I understand the `5 min = 1545 m` comment below
https://github.com/OceanParcels/Virtual_ship_classroom/blob/b9a1dbffb1e0389bf02e14babfb732d677efa157/virtualship.py#L95

Is this because the ship travels at 10 knots? Be a bit more clear?

**Comment by ammedd** [comment]
Clarified
