### ISSUE TITLE
Redundant check for point-in-region?

### ISSUE THREAD

**Issue by erikvansebille** [OceanParcels/Virtual_ship_classroom#8]
Is the check below not already done when the json file is parsed? 

https://github.com/OceanParcels/Virtual_ship_classroom/blob/b9a1dbffb1e0389bf02e14babfb732d677efa157/virtualship.py#L107-L118

Does this mean that the check is redundant and can be removed?

**Comment by ammedd** [comment]
Yes and no. I'm using this as the boundary where sampling begins. 
There must be a more elegant solutions, but I'll keep it for now
